use_frameworks!
inhibit_all_warnings!

target 'SDKSample' do
    platform :ios, '9.0'
    pod 'SlackTextViewController'
    pod 'UsergridSDK',:git => 'https://github.com/RobertWalsh/UsergridSDK'
end

target 'WatchSample Extension' do
    platform :watchos, '2.1'
    pod 'UsergridSDK',:git => 'https://github.com/RobertWalsh/UsergridSDK'
end
