language: objective-c
osx_image: xcode7
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - xcodebuild -project ./UsergridSDK.xcodeproj -scheme UsergridSDK -sdk iphonesimulator9.0 -configuration Debug test | xcpretty -c